### PR TITLE
Add footerController to hide footer manually when panel is not open

### PR DESCRIPTION
**Pull request by Yesterday17**
Part of #20

### CODE REVIEW

**Comment by zhushenwudi** [comment]
Pull down at a slow speed by gestures, the foot control still shows that it will not hide

Occasionally, Will even white screen

**Comment by Yesterday17** [comment]
How can I reproduce it? I'm using this branch in my app and it works well.

https://github.com/ProjectAnni/annix/blob/master/lib/ui/layout/layout_mobile.dart#L43-L101

> Pull down at a slow speed by gestures, the foot control still shows that it will not hide
> 
> Occasionally, Will even white screen

**Comment by lannodev** [comment]
@Yesterday17 
I'm testing your PR in a real device and `footerController` doesn't work. When I switch to `show` or `hide` it does nothing.
Could you please create an example like [this ](https://dartpad.dev/?id=6a833cba62679260bf1a556a4fdc9043) using your PR?

**Comment by zhushenwudi** [comment]
@Yesterday17 
i retry your PR, it is okay

**Comment by zhushenwudi** [comment]
> How can I reproduce it? I'm using this branch in my app and it works well.
> 
> https://github.com/ProjectAnni/annix/blob/master/lib/ui/layout/layout_mobile.dart#L43-L101
> 
> > Pull down at a slow speed by gestures, the foot control still shows that it will not hide
> > Occasionally, Will even white screen

it can work. The precondition is that it must be specified as static in the global controller file

**Comment by Yesterday17** [comment]
> @Yesterday17 I'm testing your PR in a real device and `footerController` doesn't work. When I switch to `show` or `hide` it does nothing. Could you please create an example like [this ](https://dartpad.dev/6a833cba62679260bf1a556a4fdc9043) using your PR?

I've created an example at https://dartpad.dev/?id=fbe32aedbc444cb04d10b680522b9113

**Comment by zhushenwudi** [comment]
> > @Yesterday17 I'm testing your PR in a real device and `footerController` doesn't work. When I switch to `show` or `hide` it does nothing. Could you please create an example like [this ](https://dartpad.dev/?id=6a833cba62679260bf1a556a4fdc9043) using your PR?
> 
> I've created an example at https://dartpad.dev/?fbe32aedbc444cb04d10b680522b9113

how to use this? it only show a loop function

**Comment by Yesterday17** [comment]
> how to use this? it only show a loop function

Sorry, the `?` character should be removed.

**Comment by Yesterday17** [comment]
> how to use this? it only show a loop function

Sorry, `?` in the link should be replaced with `?id=`. [updated]

**Comment by lannodev** [comment]
@Yesterday17 
Thank you for share your solution.
I have a question, why are you using this factory?
```dart
factory WeSlideController.footer() {
    return WeSlideController(true);
}
  ````
I think the best solution is to set the value through the parameter
 ```dart
  final _footerController = WeSlideController(false);
  ```

**Comment by zhushenwudi** [comment]
Maybe it is better for users to set the factory mode, regardless of the meaning of the parameter, and it is strange to declare two identical objects at the same time

**Comment by lannodev** [comment]
I think the best solution for controller is to use named parameters, see `TextEditingController` example, can be used more than once
```dart
final _footerController = WeSlideController(initial: false);
```

**Comment by zhushenwudi** [comment]
> ```dart
> false
> ```

all right

**Review by lannodev — APPROVED** [review]

**Pull request merged**
